import '../src/__tests__/api.test'
import '../src/__tests__/dark-mode.test'
import '../src/__tests__/hash.test'
import '../src/__tests__/mode.test'
import '../src/__tests__/plugins.test'
import '../src/__tests__/prefix.test'
import '../src/__tests__/preflight.test'
import '../src/__tests__/theme.test'
