name: '🐞 Bug report'
description: Something went awry and you'd like to tell us about it.
title: '[Bug]: '
labels:
  - 🐞 Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Do you need some help?
        ======================

        The issue tracker is meant for feature requests, bug reports, and documentation issues only. This isn't the best place for
        support or usage questions. Questions here don't have as much visibility as they do elsewhere. Before
        you ask a question, here are some resources to get help first:

        - 📖 Study [the documentation](https://twind.style)
        - 🤖 Try [the playground](https://twind.run)
        - 🧭 Explore [the examples](https://twind.style/examples)
        - 📓 Consult [the API reference](https://twind.style/packages)
        - 🧵 Use [Github Discussions](https://github.com/tw-in-js/twind/discussions) for message-board style questions and discussions that would benefit from being searchable.
        - 💬 Ask questions and discuss with other Twind users in real time on [Discord Chat](https://chat.twind.style).

        ### Bug Report Template:
        https://twind.run/bug-report

        ### Test Case Starter:
        https://github.com/tw-in-js/twind/tree/main/examples/basic?file=index.html
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        Please create a [minimal reproduction](https://minimum-reproduction.wtf)

        - on [twind.run](https://twind.run/bug-report) — use the _Something broken? File a bug!_ link on the top-right, or copy the share link and then paste the link here
        - or use one of the [examples](https://github.com/tw-in-js/twind/tree/main/examples#readme) for Stackblitz or Codesandbox that reproduces the issue

        Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction
        onto a small set of volunteer maintainers and isn't scalable.

        If no reproduction is provided, the issue will be closed.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Steps to reproduce the behavior with a concise description of what you expected to happen and what you're experiencing.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - annoyance
        - serious, but I can work around it
        - blocking an upgrade
        - blocking all usage of Twind
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --binaries --browsers --npmPackages "*twind/*" --markdown`
      render: sh
      placeholder: Binaries, Browsers, Twind Packages
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      placeholder: Add any other context or screenshots about the problem here.
